### ISSUE TITLE
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败

### ISSUE THREAD

**Issue by lvqilong** [MicrosoftDocs/visualstudio-docs.zh-cn#138]
[在此处输入反馈]
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\ptvsd_repl_launcher.py", line 130, in <module>
    _run_repl()
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\ptvsd_repl_launcher.py", line 102, in _run_repl
    backend.connect(int(options.port))
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\ptvsd\repl\__init__.py", line 583, in connect
    ReplBackend.connect(self, port)
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\ptvsd\repl\__init__.py", line 178, in connect
    self.conn.connect(('127.0.0.1', port))
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
交互 Python 进程已退出。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 394742b8-d974-8b1e-5800-b0fca1ef6a54
* Version Independent ID: 3065ca4c-b293-aa89-ca76-bcf718f9e21c
* Content: [Visual Studio 中的 Python 教程步骤 0，安装](https://docs.microsoft.com/zh-cn/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-00-installation?view=vs-2019)
* Content Source: [docs/python/tutorial-working-with-python-in-visual-studio-step-00-installation.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/python/tutorial-working-with-python-in-visual-studio-step-00-installation.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by lvqilong** [comment]
若要快速测试 Python 支持，请启动 Visual Studio，按 Alt+I 打开 Python 交互窗口，然后输入 2+2。 如果看不到输出 4，请重新检查步骤。

重装无效

**Comment by srvbpigh** [comment]
Hello, @lvqilong
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@lvqilong

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team

**Comment by lvqilong** [comment]
已解决，关闭Defender防火墙即可
